CREATE TABLE 社員データ AS
SELECT
    A.*
FROM
    社員マスタ A
    INNER JOIN 社員マスタ B;

ALTER TABLE
    社員データ
ADD
    COLUMN ROWKEY SERIAL FIRST;

ALTER TABLE
    社員データ CHANGE ROWKEY ROWKEY BIGINT NOT NULL;

ALTER TABLE
    社員データ DROP INDEX ROWKEY;

ALTER TABLE
    社員データ
ADD
    PRIMARY KEY(ROWKEY);